### PR TITLE
Enable ppc64le; build against TexLive 2018

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Rebuild for ppc64le;
Note - set icu to 58 due to the new texlive rebuild, which needed poppler 64/65, which wants cairo 1.14, which wants icu 58.
Do not merge yet. I'll investigate this.

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

File: recipe/meta.yaml [hunk 1]
```diff
@@ -103,7 +103,7 @@ requirements:
     - {{native}}libpng                   # [win]
     - pango                              # [not win]
     - {{native}}icu                      # [win]
-    - icu                                # [not win]
+    - icu 58.2                           # [not win]
```
Comment (bgruening) [inline recipe/meta.yaml]: I don't think this is a good idea. We need to follow the overall pinning of conda-forge here.

Comment (jayfurmanek) [reply recipe/meta.yaml]: Yea, I'm trying to find ways around that. Texlive-core 20180414 doesn't work with the latest poppler as far as I can tell (I tried). The current recipe has a patch to work with poppler 0.64/0.65 and I found a separate patch for to work with poppler 0.66, but the latest version (0.80) fails the texlive config. Poppler in the 0.60's has a dependency on cairo 1.14 and cairo 1.14 depends on ICU 58.2.

The current r-base recipe has icu 64.2, but I'm curious how that works since there is no texlive version that *should* work with those levels. I must be missing something..

Comment (jayfurmanek) [reply recipe/meta.yaml]: For an experiement in the CI, I removed the pin. Now we get ICU mismatches:

```
../../lib/libR.so: undefined reference to `u_versionToString_58'
..
```

Comment (jayfurmanek) [reply recipe/meta.yaml]: @mingwandroid What do you think? 

We could try refreshing texlive up to the 2019 level, and maybe that works with the newer poppler/cairo/icu versions. I've not tried that.

Comment (isuruf) [reply recipe/meta.yaml]: That issue is because R is picking up `icu` from the build environment.

Comment (jayfurmanek) [reply recipe/meta.yaml]: Well, it is building R at the time, right?

Comment (isuruf) [reply recipe/meta.yaml]: Yes. Try adding `icu` to build as well. (I know it's a hack, but let's see if that works)

Comment (jayfurmanek) [reply recipe/meta.yaml]: ah ok

Comment (jayfurmanek) [reply recipe/meta.yaml]: I thought it was working for a minute, but still failed the same..

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

File: recipe/meta.yaml (hunk 1 above)
Comment (jayfurmanek) [reply recipe/meta.yaml]: @isuruf Any other ideas? It looks like the oldest version of poppler that depends on the *newer* cairo (and therefor the newer ICU) is poppler 0.78. I didn't try that version specifically with a Texlive package rebuild, but 0.80 was definitely too new.

The older TexLive build didn't have a poppler dependency, but it still required cairo 1.14, which wants ICU 58, so I'm still curious how r-base works currently with the build req on ICU 64..

File: recipe/build.sh [hunk 2]
```diff
@@ -3,6 +3,9 @@
 aclocal -I m4
 autoconf
 
+# Delete ICU headers from BUILD_PREFIX
+rm -rf $BUILD_PREFIX/include/unicode
```
Comment (jayfurmanek) [inline recipe/build.sh]: Clever! It looks like this works.

**Comment by jayfurmanek** [comment]
win2008 failure is unexpected, I think?

**Comment by jayfurmanek** [comment]
I'm afraid I'm not much use debugging old windows stuff. Did we somehow break win2008?

**Comment by isuruf** [comment]
You can ignore that.( There shouldn't be two check vs2008 vs vs2015 for this repo, but I haven't been able to figure that out yet)

**Comment by jayfurmanek** [comment]
Gotcha. Anything else you recommend for this PR then?

**Comment by jayfurmanek** [comment]
@conda-forge/r  
Hello magnificent R contributors! I have a PR here to enable `r-base` for a brand new architecture to play with: ppc64le.  I'd love some feedback on this PR and your approval to merge this in. The benefits include a new set of users to conda-forge and a least a few contributors and/or maintainers as well.

Details in the PR include a move up to a newer TexLive-core version (2018), which was recently added to conda-forge, and a bit of a workaround for a mismatched ICU lib at build time. (thanks @isuruf !) 

I'm hoping that once this is in, to kick off another efforts to add ppc64le to many of the R packages in conda-forge. A fresh look and rebuild will likely be a good thing. Also, the hope is to follow this with builds for aarch64 as well once a few more of the dependencies are available on that arch.

Please let me know of any concerns, comments, or feedback on the PR please. Thank you!

**Comment by jayfurmanek** [comment]
@bgruening @dpryan79 @isuruf @jdblischak @johanneskoester @mingwandroid, @ocefpaf @sodre
Can I get a review guys? I'm willing to help maintain this for ppc64le arch if necessary.

Thanks!!

**Comment by mingwandroid** [comment]
I don't see the ppc64le build, is it enabled? How is that done?

**Comment by jayfurmanek** [comment]
Hi @mingwandroid thanks for looking.
Travis-ci.org has native ppc64le hardware now and conda-smithy has been enabled to generate build scripts for it.

For this PR, I added `provider: {linux_ppc64le: default}` to the conda-forge.yaml and did a rerender and that worked to generate the needed ppc64le scripts.

The other change in the `build.sh` script is to workaround a conflict in ICU levels between r-base and texlive-core, the latter of which still has a few dependency pins that require ICU 58 and here we are using the latest conda-forge version (64).

There are no other changes and nothing specific for ppc64le needed to build r-base.

I do plan on starting on the large set of non noarch R packages once this is in (perhaps with the help of the arch migrator).

**Comment by jayfurmanek** [comment]
Thanks for looking!
Anyone else have comments or concerns?

**Comment by jdblischak** [comment]
> There are no other changes and nothing specific for ppc64le needed to build r-base.

As long as supporting ppc64le doesn't make it too much more complex to maintain r-base, I'm fine with this.

> I do plan on starting on the large set of non noarch R packages once this is in (perhaps with the help of the arch migrator).

That was my other concern. It'll be a decent amount of work to migrate all of the non-noarch packages. My advice would to 1) don't bump the build number since there is no reason to re-build the packages for every platform when the PR is merged, and 2) see if you can skip the other builds so that your PR is checked faster.

**Comment by jayfurmanek** [comment]
Thanks @jdblischak.
Maintenance shouldn’t be hard. Major Linux distorts already include R (perhaps not as new as here, though. I can help fix any issue that may arise.

And sure I can skip bumping the build number if that’s best. What do you mean by skipping other builds? Add temporary skip lines in PRs? With some exceptions, most of the packages build pretty quick, right?

**Comment by jdblischak** [comment]
>  What do you mean by skipping other builds? Add temporary skip lines in PRs? 

@jayfurmanek Yes, if possible this would be convenient. I know with the previous CI platforms that conda-forge used it was possible to put a skip directive in the commit message. Unfortunately as far as I know this is not possible with Azure, but I mentioned it since maybe conda-forge has a workaround.

> With some exceptions, most of the packages build pretty quick, right?

Each individual build takes anywhere from 5-15 minutes depending on the platform and package. And the queue will start to back up as you try to build 100s of R packages. It's not terrible (I've been impressed with Azure processing times), but worth trying to minimize if possible.

**Comment by jayfurmanek** [comment]
@jdblischak ok makes sense. 
@isuruf any idea if this works on azure somehow?

Speaking of queue though, we can use the arch migrator but that is set up for both aarch64 and ppc64le and at least for now, aarch64 doesn’t have all the dependencies built, so that route may not be the most appropriate.

Anything else need addressing before getting this started? :) thx!

**Comment by isuruf** [comment]
We can skip azure. I can't remember the exact phrase.

> Speaking of queue though, we can use the arch migrator but that is set up for both aarch64 and ppc64le and at least for now, aarch64 doesn’t have all the dependencies built, so that route may not be the most appropriate.

I think we should do this together to reduce the amount of work for the @conda-forge/r team unless @conda-forge/arm-arch doesn't have any plans in making r-base work soon.

**Comment by jayfurmanek** [comment]
If anyone in @conda-forge/arm-arch wants to help divide and conquer that'd be great!

**Comment by hmaarrfk** [comment]
have you tried to simply enable aarch64 as well? there should be a way to add this stack to the migrator.

The general issue is we are still stuck on gstreamer.... not fun to build up the graphicsstack. r doesn't depend on graphics??? I feel like you'll get stuck there pretty soon!

**Comment by jayfurmanek** [comment]
Aarch64 needs texlive-core first. And that was painful enough for me to get working on a platform I have first hand access to. I didn’t attempt it on aarch64. I think there are missing CDTs there as well.
For graphics it looks like R uses r-rlg which has similar dependencies (including more CDTs) to gstreamer, but it doesn’t directly depend on gstreamer.
I have some short term personal interest in getting R working as well, hence the push for it. I do plan on helping with the rest of the packages currently in the migrator (gstreamer included) once I get this one through.

**Comment by hmaarrfk** [comment]
honestly, i thought doing ppc64le and aarch64 at the same time was a little ambitious. not sure if i have the bandwidth at this time to help with texlive core. I'm sure aarch64 + python will need it soon but yeah...

**Comment by jayfurmanek** [comment]
They are actually quite similar in a lot of ways, not the least of which being the need for cos7 CDTs. The changes I made to texlive-core may really just work on aarch64, but I didn't attempt it for the same reasons as not having the bandwidth. 
Likewise, if we decide to diverge here (for now) any gotcha's I come across in the R ecosystem will likely have similar solutions for ppc64le and aarch64. One example I've already looked at was the requirement for java in r-rjava, which is provided by the openjdk package, which needs a fully build JDK to bootstrap the build. I plan on using adopopenjdk.org builds for that on ppc64le as they have builds for non-x86 arches (aarch64 included). Point being, there will be a bit of a blueprint for aarch64 whenever we come back for it.

**Comment by hmaarrfk** [comment]
lets see: https://github.com/conda-forge/texlive-core-feedstock/pull/31

**Comment by jayfurmanek** [comment]
[crosses-fingers] :)

**Comment by jayfurmanek** [comment]
Some of those pkgs it's failing for actually come from `defaults` for ppc64le, I think. That certain version of poppler `0.64` is needed because no amount of patching could get it to work with a newer version - and poppler 0.64 pulls in those other ones (cairo 1.14, icu58 etc.)

**Comment by hmaarrfk** [comment]
I see. So we need to rebuild those specific versions on conda forge.

**Comment by jayfurmanek** [comment]
Yea, that would work as well.

**Comment by jayfurmanek** [comment]
So what do you think? Worth pursuing and keeping the arches together. Or we diverge here (temporarily)?

**Comment by hmaarrfk** [comment]
i'm trying to revive poppler now. lets see what will happen. Can you create a 0.65 branch?

https://github.com/conda-forge/poppler-feedstock/commit/bd3ac5d792b582a3b1117ee37faaf709ea38840b

**Comment by jayfurmanek** [comment]
Ok. I'm not able to create a branch. @isuruf ?

**Comment by hmaarrfk** [comment]
I would like to caution against moving too fast and not using the migrator.

The ppc64le and aarch builds are not so different anymore, especially since we have drone. Without a specific issue, I think it is best to follow the migrator so as to avoid pulling in old dependencies from defaults for these strange packages.

In either case, I think this should block until
- [ ] https://github.com/conda-forge/cairo-feedstock/pull/51
- [ ] https://github.com/conda-forge/mpfr-feedstock/pull/22
- [ ] https://github.com/conda-forge/texlive-core-feedstock/pull/31

As they build ppc64le dependecies as well.

**Comment by mingwandroid** [comment]
> They are actually quite similar in a lot of ways, not the least of which being the need for cos7 CDTs. The changes I made to texlive-core may really just work on aarch64, but I didn't attempt it for the same reasons as not having the bandwidth

Agreed. I cannot think of a better pairing than AArch64 and ppc64le. They are so alike it's uncanny (and from our compiler, tooling and CDT choice perpective, deliberate). At worst you may end up patching some software due to some #defines in the kernel headers and glibc port that conflict with some of our packages, still they are easily spotted and avoided.

**Comment by mingwandroid** [comment]
@hmaarrfk while avoiding things from defaults is better, can you explain why you think it would be problematic? In the past when we used different compilers then sure! If it's just the case that our packages are too old resulting in too-old `run_export` pinning then I'd happily push for us to prioritize updating the AD builds to be built from the latest conda-forge recipe.

Still, we've largely slain the binary incompatibility dragon now.

**Comment by isuruf** [comment]
> If it's just the case that our packages are too old resulting in too-old run_exports pinning then I'd happily push for us to prioritize updating the AD builds to be built from the latest conda-forge recipe.

Could you build r-base with the conda-forge recipe then? https://github.com/AnacondaRecipes/r-base-feedstock/issues/1 has been open for a while now.

**Comment by hmaarrfk** [comment]
Mostly for consistency purposes.

Binary incompatibility is addressed, but sometimes we have updated versions of packages or in rare cases, different organization (numpy)

**Comment by hmaarrfk** [comment]
@mingwandroid, perhaps the best part of not avoiding the migrator is that this migration comes at a good time where we can cleanup some of the recipes to remove the hard pinnings. Because aarch64 doesn't exist in defualts, it is a good way to test if we accidentally left some old code in the metal file.

For example, the texlive recipe used the old way to pin dependencies, but the latest PR I submitted frees up many of them, and uses the pinnings from the global pinnings repo.

**Comment by jayfurmanek** [comment]
Thanks for all the work @hmaarrfk ! Once that texlive PR is in, we'll need to update this one (or close and push a new one) and pull out that ICU workaround in the `build.sh` file. Much better all around.
